language: node_js
node_js:
- lts/*
before_install:
- bash travis/before_install.sh
install:
- npm install
before_script:
- npm install --prefix client
script:
- npm test
- npm run build --prefix client
after_success:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash travis/deploy.sh; fi'
addons:
  ssh_known_hosts:
  - 159.89.210.122
