language: node_js
node_js:
- lts/*
before_install:
- bash travis/before_install.sh
install:
- npm install
before_script:
- npm install --prefix client
script:
- npm test
- npm run build --prefix client
after_sucess:
- bask travis/deploy.sh
